version: 1
accounts:
  - name: alice
    coins: ["20000token", "200000000stake"]
  - name: bob
    coins: ["10000token", "100000000stake"]
  - name: client1
    coins: ["500token", "1000000stake"]
  - name: client2
    coins: ["500token", "1000000stake"]
  - name: client3
    coins: ["500token", "1000000stake"]
  - name: client4
    coins: ["500token", "1000000stake"]
  - name: client5
    coins: ["500token", "1000000stake"]
  - name: client6
    coins: ["500token", "1000000stake"]
  - name: client7
    coins: ["500token", "1000000stake"]
  - name: client8
    coins: ["500token", "1000000stake"]
  - name: client9
    coins: ["500token", "1000000stake"]
  - name: client10
    coins: ["500token", "1000000stake"]
  - name: client11
    coins: ["500token", "1000000stake"]
  - name: client12
    coins: ["500token", "1000000stake"]
  - name: client13
    coins: ["500token", "1000000stake"]
  - name: client14
    coins: ["500token", "1000000stake"]
  - name: client15
    coins: ["500token", "1000000stake"]
  - name: client16
    coins: ["500token", "1000000stake"]
  - name: client17
    coins: ["500token", "1000000stake"]
  - name: client18
    coins: ["500token", "1000000stake"]
  - name: client19
    coins: ["500token", "1000000stake"]
  - name: client20
    coins: ["500token", "1000000stake"]
validators:
  - name: alice
    bonded: "100000000stake"
client:
  openapi:
    path: "docs/static/openapi.yml"
  typescript:
    path: "ts-client"
  vuex:
    path: "vue/src/store"
faucet:
  name: bob
  coins: ["5token", "100000stake"]
genesis:
  app_state:
    lottery:
      params:
        BetThresCount: 10
        LotteryFee: "5token"
        MinBetAmount: "1token"
        MaxBetAmount: "100token"
build:
  main: "./cmd/lotteryd/"
